### ISSUE TITLE
Web link https://timetrackr.shinyapps.io/timetrackr/ no longer found

### ISSUE THREAD

**Issue by RossDwyer** [jalavery/timetrackR#2]
Hello,
I've been hugely impressed by your timetrackr app, but it looks like the web [link](https://timetrackr.shinyapps.io/timetrackr/) is no longer active. 

When trying to compile the script locally in RStudio, I receive the following error:
An error has occurred
The application failed to start: exited unexpectedly with code 1

Error in value[[3L]](cond) : 
  You must register an account using setAccountInfo prior to proceeding.
Calls: local ... tryCatch -> tryCatchList -> tryCatchOne -> <Anonymous>
Execution halted

**Comment by RossDwyer** [comment]
In addition to the above point, within my R console I receiver the following error - 

Error in magick_image_readpath(path, density, depth, strip, defines) : 
  rsession: UnableToOpenBlob `/Users/jessica/Desktop/calendar_light_orange.png': No such file or directory @ error/blob.c/OpenBlob/2924

**Comment by RossDwyer** [comment]
I made the below change to hexsticker.R that solved the file location issue

library(hexSticker)
sticker(subplot = "calendar_light_orange.png", 
        s_x = 1.05, s_y = .7, s_width = 0.5, s_height = 0.6,
        h_fill = "#007CBA", h_color = "#006098",
        package = "timetrackR", p_size = 8, p_color = "#F6C65B")
        
However I still receiver this warning message in R Studio...
Uploading bundle for application: 3811821...Warning: invalid uid value replaced by that for user 'nobody'
Warning: invalid gid value replaced by that for user 'nobody'

**Comment by jalavery** [comment]
Thanks @RossDwyer for letting me know that the link is broken! I made some changes on my shinyapps.io account and didn't realize it would affect the URL. The new link is: https://laveryj.shinyapps.io/timetrackR/
